
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author klyzv
 */
public class z2 extends javax.swing.JFrame {
DefaultTableModel model;
    /**
     * Creates new form z2
     */
    public z2() {
        initComponents();
        model = new DefaultTableModel();
        model.addColumn("S");
        model.addColumn("m");
        model.addColumn("n");
        model.addColumn("x");
        model.addColumn("a");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 355));
        setResizable(false);
        setSize(new java.awt.Dimension(540, 319));
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(110, 190, 80, 30);

        jTextField2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(110, 230, 80, 30);

        jTextField3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(400, 190, 80, 30);

        jTextField4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(400, 230, 80, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Введите m");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(28, 196, 90, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Введите n");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(28, 233, 80, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Введите x");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 190, 80, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Введите a");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 230, 80, 17);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "S", "m", "n", "x", "a"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(28, 128, 474, 47);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\klyzv\\Documents\\NetBeansProjects\\l2_z2\\pic1.jpg")); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(39, 13, 453, 97);

        jButton1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton1.setText("Посчитать");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(193, 273, 121, 33);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\klyzv\\Documents\\NetBeansProjects\\l2_z2\\pic2.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 540, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    Object[] Line = new Object[5];
    
    Line[1]=jTextField1.getText();
    Line[2]=jTextField2.getText();
    Line[3]=jTextField3.getText();
    Line[4]=jTextField4.getText();
    
    int m=Integer.parseInt(jTextField1.getText());
    int n=Integer.parseInt(jTextField2.getText());
    int x=Integer.parseInt(jTextField3.getText());
    int a=Integer.parseInt(jTextField4.getText());
    
    int sn=0;
    for (int i=0; i<n; i++){
        sn+=Math.pow(Math.cos(x), 2);
    }
    
    double sm=0;
    double smm=0;
    for (int i=0; i<m; i++){
        for (int j=0; j<m; j++){
            sm+=Math.sqrt(Math.abs(Math.log(Math.pow(Math.sin(a),2))));
        }
        smm+=sm;
    }
    
    double s=sn+smm;
    
    Line[0]=Double.toString(s);
    
    model.addRow(Line);
    jTable1.setModel(model);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(z2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(z2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(z2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(z2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new z2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
